name: Duplicate Detection

on:
  pull_request:
    paths:
      - scroll.tokenlist.json

jobs:
  duplicate-detection:
    name: Duplicate Detection
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ vars.GITHUB_HEAD_REF }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run validate script
        run: node scripts/checkDuplication.mjs
